List DEFINITIONS EXPLICIT TAGS ::= BEGIN

  V ::= SEQUENCE {
    a INTEGER (0..7),
    b BOOLEAN,
    c INTEGER (0..3),
    d SEQUENCE { d1 BOOLEAN, d2 BOOLEAN } }

  List ::= SEQUENCE {
    data OCTET STRING,
    next CHOICE { linked-list List, end NULL } }

END
