--- Протокол Месенжера Сохацького v2 для паб-саб брокерів на TLS
--- https://tonpa.guru/stream/2023/2023-08-07 CHAT ASN.1.htm


CHAT-v2 DEFINITIONS IMPLICIT TAGS ::=
BEGIN

    IMPORTS ContentInfo FROM CryptographicMessageSyntax-2009
            CertificationRequest FROM PKCS-10
            Certificate FROM PKIX1Explicit-2009 ;

    Version ::= INTEGER  { v0(0), v1(1), v2(2), v3(3) }
    OS ::= ENUMERATED { apple (1), microsoft (2), google (3), ericsson (4), nokia (5), cisco (6) }

    -- 01 Authority (CA)

    Feature ::= SEQUENCE { id OCTET STRING, key OCTET STRING, value OCTET STRING, group OCTET STRING }
    AuthorityMethod ::= ENUMERATED { announce (0), enroll (1), authenticate (2), revoke (3), renew (4) }
    Authority ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       type AuthorityMethod,
       cert OCTET STRING,
       settings SEQUENCE OF feature Feature }

    -- 02 Message (MNESIA, SQLite)

    File ::= SEQUENCE {
       id OCTET STRING,
       mime OCTET STRING,
       payload ANY,
       parentid OCTET STRING }

    MessageType ::= ENUMERATED { sys (1), reply (2), forward (3), read (4), edited (5) }
    MessageStatus ::= ENUMERATED { async (1), delete (2), clear (3), update (4), edit (5) }
    MessageFeed ::= CHOICE { private [1] Privatebox, chan [2] Streambox, mailbox [4] Mailbox, group [8] Groupbox }
    Message ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       inbox OCTET STRING,
       from OCTET STRING,
       to MessageFeed,
       files SEQUENCE OF file File,
       type MessageType,
       link CHOICE { empty [1] NULL, message [2] Message },
       seenby OCTET STRING,
       repliedby OCTET STRING,
       mentioned SEQUENCE OF name OCTET STRING,
       status MessageStatus DEFAULT clear }

    -- 03 Inbox Folder Queue (MNESIA, SQLite) /Mail /Chat

    Privatebox ::= SEQUENCE { address OCTET STRING } -- /Chat
    Streambox ::= SEQUENCE { channel OCTET STRING } -- /Stream
    Groupbox ::= SEQUENCE { channel OCTET STRING } -- /Conference
    Mailbox ::= SEQUENCE { channel OCTET STRING } -- /Mail
    InboxMethod ::= ENUMERATED { get (1), erase (2) }

    Inbox ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       type InboxMethod,
       feed MessageFeed,
       messages SEQUENCE OF message Message }

    -- 04 Ack / Nack (TCP REPLY PUSH)

    Ack ::= SEQUENCE { vsn Version, id OCTET STRING, primary OCTET STRING, secondary OCTET STRING OPTIONAL }

    -- 05 Activity (TCP REPLY PUSH)

    Activity ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       nickname OCTET STRING,
       comments SEQUENCE OF comment OCTET STRING }

    -- 06 Search (LDAP Search)

    SearchStatus ::= ENUMERATED { ok (0) }
    Criteria ::= ENUMERATED { equal (0), notequal (1), like (2) }
    Scope ::= ENUMERATED { profile (0), folder (1), contact (2), member (3), room (4), chat (5), message (6) }
    Search ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       dn OCTET STRING,
       field OCTET STRING,
       value OCTET STRING,
       criteria Criteria,
       type Scope,
       status SearchStatus }

    -- 07 Subscruption (MNESIA, Pub/Sub)

    SubscriptionPresence ::= ENUMERATED { offline (1), online (2) }
    SubscriptionStatus ::= ENUMERATED { request (1), confirm (2), update (3), ignore (4), ban (5), unban (6) }
    Subscription ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       nickname OCTET STRING,
       friend OCTET STRING,
       status SubscriptionPresence,
       type SubscriptionStatus }

    -- 08 Roster (LDAP /People, /Channels, /Topics and /Servers user sub-folders)

    PersonStatus ::= ENUMERATED { req (1), auth (2), ignore (3), internal (4),
       friend (5), lastmsg (6), ban (7), banned (8), deleted (9), nonexised (10) }
    Person ::= SEQUENCE {
       id OCTET STRING,
       nickname OCTET STRING,
       avatar OCTET STRING,
       names SEQUENCE OF name OCTET STRING,
       phone OCTET STRING,
       surnames SEQUENCE OF name OCTET STRING,
       lastmsg Message,
       presence SubscriptionPresence,
       update INTEGER,
       created INTEGER,
       settings SEQUENCE OF feature Feature,
       status PersonStatus }

    Server ::= SEQUENCE { service OCTET STRING, port INTEGER, host OCTET STRING }
    RosterStatus ::= ENUMERATED {
       get (1), create (2), del (3), remove (4), nick (5), search (6),
       contact (7), add (8), update (9), list (10), patch (11), lastmsg (12) }
    Roster ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       nickname OCTET STRING,
       keys SEQUENCE OF key OCTET STRING,
       people SEQUENCE OF contact Person,
       topics SEQUENCE OF room Conference,
       channels SEQUENCE OF room Conference,
       servers SEQUENCE OF server Server,
       update INTEGER,
       status RosterStatus }

    -- 09 Conference (RocksDB, Multi-user Conferences)

    MemberStatus ::= ENUMERATED { admin (1), member (2), removed (3), patch (4), owner (5) }
    Member ::= SEQUENCE {
       id OCTET STRING,
       nickname OCTET STRING,
       feed MessageFeed,
       feeds SEQUENCE OF feed OCTET STRING,
       phone OCTET STRING,
       avatar OCTET STRING,
       names SEQUENCE OF name OCTET STRING,
       surnames SEQUENCE OF name OCTET STRING,
       alias OCTET STRING,
       update INTEGER,
       settings SEQUENCE OF feature Feature,
       presence SubscriptionPresence,
       status MemberStatus }

    ConferenceType ::= ENUMERATED { group (1), channel (2), call (3) }
    ConferenceStatus ::= ENUMERATED { create (1), leave (2), add (3), remove (4), removed (5),
       join (6), joined (7), info (8), patch (9), get (10), delete (11), lastmsg (12), mute (13), unmute (14) }
    Conference ::= SEQUENCE {
       id OCTET STRING,
       vsn Version,
       session OCTET STRING,
       name OCTET STRING,
       links SEQUENCE OF link OCTET STRING,
       description OCTET STRING,
       settings SEQUENCE OF feature Feature,
       members SEQUENCE OF member Member,
       admins SEQUENCE OF member Member,
       data SEQUENCE OF file File,
       type ConferenceType,
       tos OCTET STRING,
       unread INTEGER,
       mentions SEQUENCE OF contact INTEGER,
       lastmsg Message,
       update INTEGER,
       created INTEGER,
       status ConferenceStatus }

    -- 12 CHAT-v2 Protocol Entities

    CHATProtocol ::= CHOICE {
       authority    [1] Authority,
       message      [2] Message,
       inbox        [3] Inbox,
       ack          [4] Ack,
       activity     [5] Activity,
       subscription [6] Subscription,
       search       [7] Search,
       roster       [8] Roster,
       conference   [9] Conference
    }

    CHATMessage ::= SEQUENCE {
       no INTEGER,
       headers SEQUENCE OF header OCTET STRING,
       body CHATProtocol }

END
