// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Contact: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var avatar: ASN1OctetString
    @usableFromInline var names: [ASN1OctetString]
    @usableFromInline var phone_id: ASN1OctetString
    @usableFromInline var surnames: [ASN1OctetString]
    @usableFromInline var last_msg: CHAT_Message
    @usableFromInline var presence: CHAT_PresenceType
    @usableFromInline var update: ArraySlice<UInt8>
    @usableFromInline var created: ArraySlice<UInt8>
    @usableFromInline var settings: [CHAT_Feature]
    @usableFromInline var services: [CHAT_Service]
    @usableFromInline var status: CHAT_ContactStatus
    @inlinable init(nickname: ASN1OctetString, avatar: ASN1OctetString, names: [ASN1OctetString], phone_id: ASN1OctetString, surnames: [ASN1OctetString], last_msg: CHAT_Message, presence: CHAT_PresenceType, update: ArraySlice<UInt8>, created: ArraySlice<UInt8>, settings: [CHAT_Feature], services: [CHAT_Service], status: CHAT_ContactStatus) {
        self.nickname = nickname
        self.avatar = avatar
        self.names = names
        self.phone_id = phone_id
        self.surnames = surnames
        self.last_msg = last_msg
        self.presence = presence
        self.update = update
        self.created = created
        self.settings = settings
        self.services = services
        self.status = status

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let avatar: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let names: [ASN1OctetString] = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let phone_id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let surnames: [ASN1OctetString] = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let last_msg: CHAT_Message = try CHAT_Message(derEncoded: &nodes)
            let presence: CHAT_PresenceType = try CHAT_PresenceType(derEncoded: &nodes)
            let update: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let created: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let settings: [CHAT_Feature] = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, nodes: &nodes)
            let services: [CHAT_Service] = try DER.sequence(of: CHAT_Service.self, identifier: .sequence, nodes: &nodes)
            let status: CHAT_ContactStatus = try CHAT_ContactStatus(derEncoded: &nodes)

            return CHAT_Contact(nickname: nickname, avatar: avatar, names: names, phone_id: phone_id, surnames: surnames, last_msg: last_msg, presence: presence, update: update, created: created, settings: settings, services: services, status: status)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(nickname)
            try coder.serialize(avatar)
            try coder.serializeSequenceOf(names)
            try coder.serialize(phone_id)
            try coder.serializeSequenceOf(surnames)
            try coder.serialize(last_msg)
            try coder.serialize(presence)
            try coder.serialize(update)
            try coder.serialize(created)
            try coder.serializeSequenceOf(settings)
            try coder.serializeSequenceOf(services)
            try coder.serialize(status)

        }
    }
}
