// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Friend: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var friend: ASN1OctetString
    @usableFromInline var type: CHAT_Friendship
    @inlinable init(nickname: ASN1OctetString, friend: ASN1OctetString, type: CHAT_Friendship) {
        self.nickname = nickname
        self.friend = friend
        self.type = type

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let friend: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let type: CHAT_Friendship = try CHAT_Friendship(derEncoded: &nodes)

            return CHAT_Friend(nickname: nickname, friend: friend, type: type)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(nickname)
            try coder.serialize(friend)
            try coder.serialize(type)

        }
    }
}
