// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum CHAT_Protocol: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case register(CHAT_Register)
    case auth(CHAT_Auth)
    case feature(CHAT_Feature)
    case service(CHAT_Service)
    case message(CHAT_Message)
    case profile(CHAT_Profile)
    case room(CHAT_Room)
    case member(CHAT_Member)
    case search(CHAT_Search)
    case file(CHAT_FileDesc)
    case typing(CHAT_Typing)
    case friend(CHAT_Friend)
    case presence(CHAT_Presence)
    case history(CHAT_History)
    case roster(CHAT_Roster)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
        case ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific):
            self = .register(try CHAT_Register(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific):
            self = .auth(try CHAT_Auth(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific):
            self = .feature(try CHAT_Feature(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
            self = .service(try CHAT_Service(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific):
            self = .message(try CHAT_Message(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific):
            self = .profile(try CHAT_Profile(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific):
            self = .room(try CHAT_Room(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific):
            self = .member(try CHAT_Member(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific):
            self = .search(try CHAT_Search(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific):
            self = .file(try CHAT_FileDesc(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 10, tagClass: .contextSpecific):
            self = .typing(try CHAT_Typing(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 11, tagClass: .contextSpecific):
            self = .friend(try CHAT_Friend(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 12, tagClass: .contextSpecific):
            self = .presence(try CHAT_Presence(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 13, tagClass: .contextSpecific):
            self = .history(try CHAT_History(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case ASN1Identifier(tagWithNumber: 14, tagClass: .contextSpecific):
            self = .roster(try CHAT_Roster(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
        case .register(let register): try register.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
        case .auth(let auth): try auth.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
        case .feature(let feature): try feature.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
        case .service(let service): try service.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
        case .message(let message): try message.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific))
        case .profile(let profile): try profile.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific))
        case .room(let room): try room.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific))
        case .member(let member): try member.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific))
        case .search(let search): try search.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific))
        case .file(let file): try file.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific))
        case .typing(let typing): try typing.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 10, tagClass: .contextSpecific))
        case .friend(let friend): try friend.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 11, tagClass: .contextSpecific))
        case .presence(let presence): try presence.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 12, tagClass: .contextSpecific))
        case .history(let history): try history.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 13, tagClass: .contextSpecific))
        case .roster(let roster): try roster.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 14, tagClass: .contextSpecific))

        }
    }

}
