// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Auth: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var session: ASN1OctetString
    @usableFromInline var type: CHAT_AuthType
    @usableFromInline var sms_code: ASN1OctetString
    @usableFromInline var cert: ASN1OctetString
    @usableFromInline var challange: ASN1OctetString
    @usableFromInline var push: ASN1OctetString
    @usableFromInline var os: CHAT_OS
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var settings: [CHAT_Feature]
    @usableFromInline var token: ASN1OctetString
    @usableFromInline var devkey: ASN1OctetString
    @usableFromInline var phone: ASN1OctetString
    @inlinable init(session: ASN1OctetString, type: CHAT_AuthType, sms_code: ASN1OctetString, cert: ASN1OctetString, challange: ASN1OctetString, push: ASN1OctetString, os: CHAT_OS, nickname: ASN1OctetString, settings: [CHAT_Feature], token: ASN1OctetString, devkey: ASN1OctetString, phone: ASN1OctetString) {
        self.session = session
        self.type = type
        self.sms_code = sms_code
        self.cert = cert
        self.challange = challange
        self.push = push
        self.os = os
        self.nickname = nickname
        self.settings = settings
        self.token = token
        self.devkey = devkey
        self.phone = phone

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let session: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let type: CHAT_AuthType = try CHAT_AuthType(derEncoded: &nodes)
            let sms_code: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let cert: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let challange: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let push: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let os: CHAT_OS = try CHAT_OS(derEncoded: &nodes)
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let settings: [CHAT_Feature] = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, nodes: &nodes)
            let token: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let devkey: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let phone: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)

            return CHAT_Auth(session: session, type: type, sms_code: sms_code, cert: cert, challange: challange, push: push, os: os, nickname: nickname, settings: settings, token: token, devkey: devkey, phone: phone)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(session)
            try coder.serialize(type)
            try coder.serialize(sms_code)
            try coder.serialize(cert)
            try coder.serialize(challange)
            try coder.serialize(push)
            try coder.serialize(os)
            try coder.serialize(nickname)
            try coder.serializeSequenceOf(settings)
            try coder.serialize(token)
            try coder.serialize(devkey)
            try coder.serialize(phone)

        }
    }
}
