// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct CHAT_ContactStatus: DERImplicitlyTaggable, Sendable, RawRepresentable {
    public static var defaultIdentifier: ASN1Identifier { .enumerated }
    public var rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
    public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try .init(derEncoded: rootNode, withIdentifier: identifier)
    }
    public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    static let request = Self(rawValue: 1)
    static let authorization = Self(rawValue: 2)
    static let ignore = Self(rawValue: 3)
    static let intern = Self(rawValue: 4)
    static let friend = Self(rawValue: 5)
    static let last_msg = Self(rawValue: 6)
    static let ban = Self(rawValue: 7)
    static let banned = Self(rawValue: 8)
    static let deleted = Self(rawValue: 9)
    static let nonexised = Self(rawValue: 10)
}
