// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Roster: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var update: ArraySlice<UInt8>
    @usableFromInline var contacts: [CHAT_Contact]
    @usableFromInline var topics: [CHAT_Room]
    @usableFromInline var status: CHAT_RosterStatus
    @inlinable init(id: ASN1OctetString, nickname: ASN1OctetString, update: ArraySlice<UInt8>, contacts: [CHAT_Contact], topics: [CHAT_Room], status: CHAT_RosterStatus) {
        self.id = id
        self.nickname = nickname
        self.update = update
        self.contacts = contacts
        self.topics = topics
        self.status = status

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let update: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let contacts: [CHAT_Contact] = try DER.sequence(of: CHAT_Contact.self, identifier: .sequence, nodes: &nodes)
            let topics: [CHAT_Room] = try DER.sequence(of: CHAT_Room.self, identifier: .sequence, nodes: &nodes)
            let status: CHAT_RosterStatus = try CHAT_RosterStatus(derEncoded: &nodes)

            return CHAT_Roster(id: id, nickname: nickname, update: update, contacts: contacts, topics: topics, status: status)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(nickname)
            try coder.serialize(update)
            try coder.serializeSequenceOf(contacts)
            try coder.serializeSequenceOf(topics)
            try coder.serialize(status)

        }
    }
}
