// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Server: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var service: ASN1OctetString
    @usableFromInline var port: ArraySlice<UInt8>
    @usableFromInline var host: ASN1OctetString
    @inlinable init(service: ASN1OctetString, port: ArraySlice<UInt8>, host: ASN1OctetString) {
        self.service = service
        self.port = port
        self.host = host

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let service: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let port: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let host: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)

            return CHAT_Server(service: service, port: port, host: host)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(service)
            try coder.serialize(port)
            try coder.serialize(host)

        }
    }
}
