// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Message: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var feed_id: CHAT_Message_feed_id_Choice
    @usableFromInline var signature: ASN1OctetString
    @usableFromInline var from: ASN1OctetString
    @usableFromInline var to: ASN1OctetString
    @usableFromInline var created: ArraySlice<UInt8>
    @usableFromInline var files: [CHAT_FileDesc]
    @usableFromInline var type: CHAT_MessageType
    @usableFromInline var link: ArraySlice<UInt8>
    @usableFromInline var seenby: ASN1OctetString
    @usableFromInline var repliedby: ASN1OctetString
    @usableFromInline var mentioned: [ASN1OctetString]
    @usableFromInline var status: CHAT_MessageStatus

    @inlinable init(id: ASN1OctetString, feed_id: CHAT_Message_feed_id_Choice, signature: ASN1OctetString, from: ASN1OctetString, to: ASN1OctetString, created: ArraySlice<UInt8>, files: [CHAT_FileDesc], type: CHAT_MessageType, link: ArraySlice<UInt8>, seenby: ASN1OctetString, repliedby: ASN1OctetString, mentioned: [ASN1OctetString], status: CHAT_MessageStatus) {
        self.id = id
        self.feed_id = feed_id
        self.signature = signature
        self.from = from
        self.to = to
        self.created = created
        self.files = files
        self.type = type
        self.link = link
        self.seenby = seenby
        self.repliedby = repliedby
        self.mentioned = mentioned
        self.status = status
    }

    @inlinable init(derEncoded root: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id = try ASN1OctetString(derEncoded: &nodes)
            let feed_id = try CHAT_Message_feed_id_Choice(derEncoded: &nodes)
            let signature = try ASN1OctetString(derEncoded: &nodes)
            let from = try ASN1OctetString(derEncoded: &nodes)
            let to = try ASN1OctetString(derEncoded: &nodes)
            let created = try ArraySlice<UInt8>(derEncoded: &nodes)
            let files = try DER.sequence(of: CHAT_FileDesc.self, identifier: .sequence, nodes: &nodes)
            let type = try CHAT_MessageType(derEncoded: &nodes)
            let link = try ArraySlice<UInt8>(derEncoded: &nodes)
            let seenby = try ASN1OctetString(derEncoded: &nodes)
            let repliedby = try ASN1OctetString(derEncoded: &nodes)
            let mentioned = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let status = try CHAT_MessageStatus(derEncoded: &nodes)

            return CHAT_Message(id: id, feed_id: feed_id, signature: signature, from: from, to: to, created: created, files: files, type: type, link: link, seenby: seenby, repliedby: repliedby, mentioned: mentioned, status: status)
        }
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(feed_id)
            try coder.serialize(signature)
            try coder.serialize(from)
            try coder.serialize(to)
            try coder.serialize(created)
            try coder.serializeSequenceOf(files)
            try coder.serialize(type)
            try coder.serialize(link)
            try coder.serialize(seenby)
            try coder.serialize(repliedby)
            try coder.serializeSequenceOf(mentioned)
            try coder.serialize(status)
        }
    }
}
