// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct CHAT_RosterStatus: DERImplicitlyTaggable, Sendable, RawRepresentable {
    public static var defaultIdentifier: ASN1Identifier { .enumerated }
    public var rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
    public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try .init(derEncoded: rootNode, withIdentifier: identifier)
    }
    public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    static let get = Self(rawValue: 1)
    static let create = Self(rawValue: 2)
    static let del = Self(rawValue: 3)
    static let remove = Self(rawValue: 4)
    static let nick = Self(rawValue: 5)
    static let search = Self(rawValue: 6)
    static let contact = Self(rawValue: 7)
    static let add = Self(rawValue: 8)
    static let update = Self(rawValue: 9)
    static let list = Self(rawValue: 10)
    static let patch = Self(rawValue: 11)
    static let last_msg = Self(rawValue: 12)
}
