// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Service: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var type: CHAT_ServiceType
    @usableFromInline var data: ASN1OctetString
    @usableFromInline var login: ASN1OctetString
    @usableFromInline var password: ASN1OctetString
    @usableFromInline var expiration: ArraySlice<UInt8>
    @usableFromInline var status: CHAT_ServiceStatus
    @inlinable init(id: ASN1OctetString, type: CHAT_ServiceType, data: ASN1OctetString, login: ASN1OctetString, password: ASN1OctetString, expiration: ArraySlice<UInt8>, status: CHAT_ServiceStatus) {
        self.id = id
        self.type = type
        self.data = data
        self.login = login
        self.password = password
        self.expiration = expiration
        self.status = status

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let type: CHAT_ServiceType = try CHAT_ServiceType(derEncoded: &nodes)
            let data: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let login: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let password: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let expiration: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let status: CHAT_ServiceStatus = try CHAT_ServiceStatus(derEncoded: &nodes)

            return CHAT_Service(id: id, type: type, data: data, login: login, password: password, expiration: expiration, status: status)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(type)
            try coder.serialize(data)
            try coder.serialize(login)
            try coder.serialize(password)
            try coder.serialize(expiration)
            try coder.serialize(status)

        }
    }
}
