// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct CHAT_RoomStatus: DERImplicitlyTaggable, Sendable, RawRepresentable {
    public static var defaultIdentifier: ASN1Identifier { .enumerated }
    public var rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
    public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try .init(derEncoded: rootNode, withIdentifier: identifier)
    }
    public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    static let create = Self(rawValue: 1)
    static let leave = Self(rawValue: 2)
    static let add = Self(rawValue: 3)
    static let remove = Self(rawValue: 4)
    static let removed = Self(rawValue: 5)
    static let join = Self(rawValue: 6)
    static let joined = Self(rawValue: 7)
    static let info = Self(rawValue: 8)
    static let patch = Self(rawValue: 9)
    static let get = Self(rawValue: 10)
    static let delete = Self(rawValue: 11)
    static let last_msg = Self(rawValue: 12)
    static let mute = Self(rawValue: 13)
    static let unmute = Self(rawValue: 14)
}
