// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Presence: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var status: CHAT_PresenceType
    @inlinable init(nickname: ASN1OctetString, status: CHAT_PresenceType) {
        self.nickname = nickname
        self.status = status

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let status: CHAT_PresenceType = try CHAT_PresenceType(derEncoded: &nodes)

            return CHAT_Presence(nickname: nickname, status: status)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(nickname)
            try coder.serialize(status)

        }
    }
}
