// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Room: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var name: ASN1OctetString
    @usableFromInline var links: [ASN1OctetString]
    @usableFromInline var description: ASN1OctetString
    @usableFromInline var settings: [CHAT_Feature]
    @usableFromInline var members: [CHAT_Member]
    @usableFromInline var admins: [CHAT_Member]
    @usableFromInline var data: [CHAT_FileDesc]
    @usableFromInline var type: CHAT_RoomType
    @usableFromInline var tos: ASN1OctetString
    @usableFromInline var tos_update: ArraySlice<UInt8>
    @usableFromInline var unread: ArraySlice<UInt8>
    @usableFromInline var mentions: [ArraySlice<UInt8>]
    @usableFromInline var last_msg: CHAT_Message
    @usableFromInline var update: ArraySlice<UInt8>
    @usableFromInline var created: ArraySlice<UInt8>
    @usableFromInline var status: CHAT_RoomStatus
    @inlinable init(id: ASN1OctetString, name: ASN1OctetString, links: [ASN1OctetString], description: ASN1OctetString, settings: [CHAT_Feature], members: [CHAT_Member], admins: [CHAT_Member], data: [CHAT_FileDesc], type: CHAT_RoomType, tos: ASN1OctetString, tos_update: ArraySlice<UInt8>, unread: ArraySlice<UInt8>, mentions: [ArraySlice<UInt8>], last_msg: CHAT_Message, update: ArraySlice<UInt8>, created: ArraySlice<UInt8>, status: CHAT_RoomStatus) {
        self.id = id
        self.name = name
        self.links = links
        self.description = description
        self.settings = settings
        self.members = members
        self.admins = admins
        self.data = data
        self.type = type
        self.tos = tos
        self.tos_update = tos_update
        self.unread = unread
        self.mentions = mentions
        self.last_msg = last_msg
        self.update = update
        self.created = created
        self.status = status

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let name: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let links: [ASN1OctetString] = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let description: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let settings: [CHAT_Feature] = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, nodes: &nodes)
            let members: [CHAT_Member] = try DER.sequence(of: CHAT_Member.self, identifier: .sequence, nodes: &nodes)
            let admins: [CHAT_Member] = try DER.sequence(of: CHAT_Member.self, identifier: .sequence, nodes: &nodes)
            let data: [CHAT_FileDesc] = try DER.sequence(of: CHAT_FileDesc.self, identifier: .sequence, nodes: &nodes)
            let type: CHAT_RoomType = try CHAT_RoomType(derEncoded: &nodes)
            let tos: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let tos_update: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let unread: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let mentions: [ArraySlice<UInt8>] = try DER.sequence(of: ArraySlice<UInt8>.self, identifier: .sequence, nodes: &nodes)
            let last_msg: CHAT_Message = try CHAT_Message(derEncoded: &nodes)
            let update: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let created: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let status: CHAT_RoomStatus = try CHAT_RoomStatus(derEncoded: &nodes)

            return CHAT_Room(id: id, name: name, links: links, description: description, settings: settings, members: members, admins: admins, data: data, type: type, tos: tos, tos_update: tos_update, unread: unread, mentions: mentions, last_msg: last_msg, update: update, created: created, status: status)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(name)
            try coder.serializeSequenceOf(links)
            try coder.serialize(description)
            try coder.serializeSequenceOf(settings)
            try coder.serializeSequenceOf(members)
            try coder.serializeSequenceOf(admins)
            try coder.serializeSequenceOf(data)
            try coder.serialize(type)
            try coder.serialize(tos)
            try coder.serialize(tos_update)
            try coder.serialize(unread)
            try coder.serializeSequenceOf(mentions)
            try coder.serialize(last_msg)
            try coder.serialize(update)
            try coder.serialize(created)
            try coder.serialize(status)

        }
    }
}
