// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_FileDesc: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var mime: ASN1OctetString
    @usableFromInline var payload: ASN1Any
    @usableFromInline var parentid: ASN1OctetString
    @usableFromInline var data: [CHAT_Feature]
    @inlinable init(id: ASN1OctetString, mime: ASN1OctetString, payload: ASN1Any, parentid: ASN1OctetString, data: [CHAT_Feature]) {
        self.id = id
        self.mime = mime
        self.payload = payload
        self.parentid = parentid
        self.data = data

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let mime: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let payload: ASN1Any = try ASN1Any(derEncoded: &nodes)
            let parentid: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let data: [CHAT_Feature] = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, nodes: &nodes)

            return CHAT_FileDesc(id: id, mime: mime, payload: payload, parentid: parentid, data: data)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(mime)
            try coder.serialize(payload)
            try coder.serialize(parentid)
            try coder.serializeSequenceOf(data)

        }
    }
}
