// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Profile: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var nickname: ASN1OctetString
    @usableFromInline var phone: ASN1OctetString
    @usableFromInline var session: ASN1OctetString
    @usableFromInline var chats: [CHAT_Contact]
    @usableFromInline var contacts: [CHAT_Contact]
    @usableFromInline var keys: [ASN1OctetString]
    @usableFromInline var servers: [CHAT_Server]
    @usableFromInline var settings: [CHAT_Feature]
    @usableFromInline var update: ArraySlice<UInt8>
    @usableFromInline var status: ArraySlice<UInt8>
    @usableFromInline var roster: CHAT_Roster
    @inlinable init(nickname: ASN1OctetString, phone: ASN1OctetString, session: ASN1OctetString, chats: [CHAT_Contact], contacts: [CHAT_Contact], keys: [ASN1OctetString], servers: [CHAT_Server], settings: [CHAT_Feature], update: ArraySlice<UInt8>, status: ArraySlice<UInt8>, roster: CHAT_Roster) {
        self.nickname = nickname
        self.phone = phone
        self.session = session
        self.chats = chats
        self.contacts = contacts
        self.keys = keys
        self.servers = servers
        self.settings = settings
        self.update = update
        self.status = status
        self.roster = roster

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let nickname: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let phone: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let session: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let chats: [CHAT_Contact] = try DER.sequence(of: CHAT_Contact.self, identifier: .sequence, nodes: &nodes)
            let contacts: [CHAT_Contact] = try DER.sequence(of: CHAT_Contact.self, identifier: .sequence, nodes: &nodes)
            let keys: [ASN1OctetString] = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let servers: [CHAT_Server] = try DER.sequence(of: CHAT_Server.self, identifier: .sequence, nodes: &nodes)
            let settings: [CHAT_Feature] = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, nodes: &nodes)
            let update: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let status: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let roster: CHAT_Roster = try CHAT_Roster(derEncoded: &nodes)

            return CHAT_Profile(nickname: nickname, phone: phone, session: session, chats: chats, contacts: contacts, keys: keys, servers: servers, settings: settings, update: update, status: status, roster: roster)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(nickname)
            try coder.serialize(phone)
            try coder.serialize(session)
            try coder.serializeSequenceOf(chats)
            try coder.serializeSequenceOf(contacts)
            try coder.serializeSequenceOf(keys)
            try coder.serializeSequenceOf(servers)
            try coder.serializeSequenceOf(settings)
            try coder.serialize(update)
            try coder.serialize(status)
            try coder.serialize(roster)

        }
    }
}
