// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct CHAT_HistoryStatus: DERImplicitlyTaggable, Sendable, RawRepresentable {
    public static var defaultIdentifier: ASN1Identifier { .enumerated }
    public var rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
    public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try .init(derEncoded: rootNode, withIdentifier: identifier)
    }
    public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    static let updated = Self(rawValue: 1)
    static let get = Self(rawValue: 2)
    static let update = Self(rawValue: 3)
    static let last_loaded = Self(rawValue: 4)
    static let last_msg = Self(rawValue: 5)
    static let get_reply = Self(rawValue: 6)
    static let double_get = Self(rawValue: 7)
    static let delete = Self(rawValue: 8)
    static let image = Self(rawValue: 9)
    static let video = Self(rawValue: 10)
    static let file = Self(rawValue: 11)
    static let link = Self(rawValue: 12)
    static let audio = Self(rawValue: 13)
    static let contact = Self(rawValue: 14)
    static let location = Self(rawValue: 15)
    static let text = Self(rawValue: 16)
}
