%% Generated by the Erlang ASN.1 compiler. Version: 5.4.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CHAT-v2.

-ifndef(_CHAT_V2_HRL_).
-define(_CHAT_V2_HRL_, true).

-record('Feature', {
  id,
  key,
  value,
  group
}).

-record('Authority', {
  id,
  vsn,
  session,
  type,
  cert,
  settings
}).

-record('File', {
  id,
  mime,
  payload,
  parentid
}).

-record('Message', {
  id,
  vsn,
  session,
  from,
  to,
  files,
  type,
  link,
  seenby,
  repliedby,
  mentioned,
  status = asn1_DEFAULT
}).

-record('Privatebox', {
  address
}).

-record('Streambox', {
  channel
}).

-record('Groupbox', {
  channel
}).

-record('Mailbox', {
  channel
}).

-record('Inbox', {
  id,
  vsn,
  session,
  type,
  feed,
  messages
}).

-record('Ack', {
  vsn,
  id,
  primary,
  secondary = asn1_NOVALUE
}).

-record('Activity', {
  id,
  vsn,
  session,
  nickname,
  comments
}).

-record('Search', {
  id,
  vsn,
  session,
  dn,
  field,
  value,
  criteria,
  type,
  status
}).

-record('Subscription', {
  id,
  vsn,
  session,
  nickname,
  friend,
  status,
  type
}).

-record('Person', {
  id,
  nickname,
  avatar,
  names,
  phone,
  surnames,
  lastmsg,
  presence,
  update,
  created,
  settings,
  status
}).

-record('Server', {
  service,
  port,
  host
}).

-record('Roster', {
  id,
  vsn,
  session,
  nickname,
  keys,
  people,
  topics,
  channels,
  servers,
  update,
  status
}).

-record('Member', {
  id,
  nickname,
  feed,
  feeds,
  phone,
  avatar,
  names,
  surnames,
  alias,
  update,
  settings,
  presence,
  status
}).

-record('Conference', {
  id,
  vsn,
  session,
  name,
  links,
  description,
  settings,
  members,
  admins,
  data,
  type,
  tos,
  unread,
  mentions,
  lastmsg,
  update,
  created,
  status
}).

-record('CHATMessage', {
  no,
  headers,
  body
}).

-endif. %% _CHAT_V2_HRL_
