%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CHAT.

-ifndef(_CHAT_HRL_).
-define(_CHAT_HRL_, true).

-record('IO', {
  data,
  code
}).

-record('OK', {
  data
}).

-record('ERROR', {
  code
}).

-record('P2P', {
  from,
  to
}).

-record('MUC', {
  room
}).

-record('Feature', {
  id,
  key,
  value,
  group
}).

-record('Service', {
  id,
  type,
  data,
  login,
  password,
  expiration,
  status
}).

-record('Register', {
  nickname,
  csr,
  password
}).

-record('Presence', {
  nickname,
  status
}).

-record('Contact', {
  nickname,
  avatar,
  names,
  phone,
  surnames,
  lastmsg,
  presence,
  update,
  created,
  settings,
  services,
  status
}).

-record('Roster', {
  id,
  nickname,
  update,
  contacts,
  topics,
  status
}).

-record('Message', {
  id,
  feed,
  signature,
  from,
  to,
  created,
  files,
  type,
  link,
  seenby,
  repliedby,
  mentioned,
  status = asn1_DEFAULT
}).

-record('Member', {
  id,
  feed,
  feeds,
  phone,
  avatar,
  names,
  surnames,
  alias,
  update,
  settings,
  services,
  presence,
  status
}).

-record('Room', {
  id,
  name,
  links,
  description,
  settings,
  members,
  admins,
  data,
  type,
  tos,
  tosupdate,
  unread,
  mentions,
  lastmsg,
  update,
  created,
  status
}).

-record('Server', {
  service,
  port,
  host
}).

-record('Profile', {
  nickname,
  phone,
  session,
  chats,
  contacts,
  keys,
  servers,
  settings,
  update,
  status,
  roster
}).

-record('Ack', {
  table,
  id
}).

-record('FileDesc', {
  id,
  mime,
  payload,
  parentid,
  data
}).

-record('Auth', {
  session,
  type,
  cert,
  challange,
  push,
  os,
  nickname,
  settings,
  token,
  devkey,
  phone
}).

-record('Search', {
  dn,
  id,
  field,
  value,
  criteria,
  type,
  status
}).

-record('Typing', {
  session,
  nickname,
  comments
}).

-record('Friend', {
  nickname,
  friend,
  type
}).

-record('History', {
  nickname,
  feed,
  size,
  entity,
  data,
  roster,
  status
}).

-record('CHATMessage', {
  no,
  headers,
  body
}).

-endif. %% _CHAT_HRL_
