%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module MESSAGE-v1.

-ifndef(_MESSAGE_V1_HRL_).
-define(_MESSAGE_V1_HRL_, true).

-record('P2P', {
  from,
  to
}).

-record('MUC', {
  room
}).

-record('Feature', {
  id,
  key,
  value,
  group
}).

-record('Authority', {
  session,
  type,
  cert,
  settings
}).

-record('File', {
  id,
  mime,
  payload,
  parentid
}).

-record('Channel', {
  channel
}).

-record('Message', {
  id,
  feed,
  from,
  to,
  files,
  type,
  link,
  seenby,
  repliedby,
  mentioned,
  status = asn1_DEFAULT
}).

-record('Ack', {
  table,
  id
}).

-endif. %% _MESSAGE_V1_HRL_
