// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline struct BinaryField: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var m: ArraySlice<UInt8>
    @usableFromInline var p: BinaryField_p_Choice?
    @inlinable init(m: ArraySlice<UInt8>, p: BinaryField_p_Choice?) {
        self.m = m
        self.p = p
    }

         @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let m: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let p: BinaryField_p_Choice? = try BinaryField_p_Choice(derEncoded: &nodes)
            return BinaryField(m: m, p: p)
        }
    }
     @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(m)
            if let p = self.p { try coder.serialize(p) }
        }
    }
 

     }
