// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline indirect enum DirectoryString: DERParseable, DERSerializable, Hashable, Sendable {
    case printableString(ASN1PrintableString)
    case utf8String(ASN1UTF8String)
    case bmpString(ASN1BMPString)
    @inlinable init(derEncoded rootNode: ASN1Node) throws {
        switch rootNode.identifier {
            case ASN1PrintableString.defaultIdentifier:
                self = .printableString(try ASN1PrintableString(derEncoded: rootNode))
            case ASN1UTF8String.defaultIdentifier:
                self = .utf8String(try ASN1UTF8String(derEncoded: rootNode))
            case ASN1BMPString.defaultIdentifier:
                self = .bmpString(try ASN1BMPString(derEncoded: rootNode))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer) throws {
        switch self {
            case .printableString(let printableString): try coder.serialize(printableString)
            case .utf8String(let utf8String): try coder.serialize(utf8String)
            case .bmpString(let bmpString): try coder.serialize(bmpString)
        }
    }

}
