// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline indirect enum DSTU4145Params_definition_Choice: DERParseable, DERSerializable, Hashable, Sendable {
    case ecbinary(ECBinary)
    case namedCurve(ASN1ObjectIdentifier)
    @inlinable init(derEncoded rootNode: ASN1Node) throws {
        switch rootNode.identifier {
            case ECBinary.defaultIdentifier:
                self = .ecbinary(try ECBinary(derEncoded: rootNode))
            case ASN1ObjectIdentifier.defaultIdentifier:
                self = .namedCurve(try ASN1ObjectIdentifier(derEncoded: rootNode))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer) throws {
        switch self {
            case .ecbinary(let ecbinary): try coder.serialize(ecbinary)
            case .namedCurve(let namedCurve): try coder.serialize(namedCurve)
        }
    }

}
