// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline struct Extension: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var extnID: ASN1ObjectIdentifier
    @usableFromInline var critical: Bool
    @usableFromInline var extnvalue: ASN1OctetString
    @inlinable init(extnID: ASN1ObjectIdentifier, critical: Bool, extnvalue: ASN1OctetString) {
        self.extnID = extnID
        self.critical = critical
        self.extnvalue = extnvalue
    }

         @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let extnID: ASN1ObjectIdentifier = try ASN1ObjectIdentifier(derEncoded: &nodes)
            let critical: Bool = try DER.decodeDefault(&nodes, defaultValue: false)
            let extnvalue = try ASN1OctetString(derEncoded: &nodes)
            return Extension(extnID: extnID, critical: critical, extnvalue: extnvalue)
        }
    }
     @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(extnID)
            try coder.serialize(critical)
            try coder.serialize(extnvalue)
        }
    }
 

     }
