// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline struct SubjectPublicKeyInfo: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var algorithm: AlgorithmIdentifier
    @usableFromInline var subjectPublicKey: ASN1BitString
    @inlinable init(algorithm: AlgorithmIdentifier, subjectPublicKey: ASN1BitString) {
        self.algorithm = algorithm
        self.subjectPublicKey = subjectPublicKey
    }

         @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let algorithm: AlgorithmIdentifier = try AlgorithmIdentifier(derEncoded: &nodes)
            let subjectPublicKey: ASN1BitString = try ASN1BitString(derEncoded: &nodes)
            return SubjectPublicKeyInfo(algorithm: algorithm, subjectPublicKey: subjectPublicKey)
        }
    }
     @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(algorithm)
            try coder.serialize(subjectPublicKey)
        }
    }
 

     }
