// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline struct Validity: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var notBefore: Time
    @usableFromInline var notAfter: Time
    @inlinable init(notBefore: Time, notAfter: Time) {
        self.notBefore = notBefore
        self.notAfter = notAfter
    }

         @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let notBefore: Time = try Time(derEncoded: &nodes)
            let notAfter: Time = try Time(derEncoded: &nodes)
            return Validity(notBefore: notBefore, notAfter: notAfter)
        }
    }
     @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(notBefore)
            try coder.serialize(notAfter)
        }
    }
 

     }
