// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
public struct Version : Hashable, Sendable, Comparable {
    @usableFromInline  var rawValue: Int
    @inlinable public static func < (lhs: Version, rhs: Version) -> Bool { lhs.rawValue < rhs.rawValue }
    @inlinable init(rawValue: Int) { self.rawValue = rawValue }
    public static let v3 = Self(rawValue: 2)
}
