%% Generated by the Erlang ASN.1 BER compiler. Version: 5.4.3
%% Purpose: Encoding and decoding of the types in MESSAGE-v1.

-module('MESSAGE-v1').
-moduledoc false.
-compile(nowarn_unused_vars).
-dialyzer(no_improper_lists).
-dialyzer(no_match).
-include_lib("chat/include/MESSAGE-v1.hrl").
-asn1_info([{vsn,'5.4.3'},
            {module,'MESSAGE-v1'},
            {options,[warnings,ber,errors,
 {cwd,"/Users/tonpa/depot/synrc/chat/priv/v1"},
 {outdir,"/Users/tonpa/depot/synrc/chat/priv/v1"},
 {i,"."},
 {i,"/Users/tonpa/depot/synrc/chat/priv/v1"}]}]).

-export([encoding_rule/0,maps/0,bit_string_format/0,
         legacy_erlang_types/0]).
-export(['dialyzer-suppressions'/1]).
-export([
enc_OS/2,
enc_P2P/2,
enc_MUC/2,
enc_CHATString/2,
enc_Feature/2,
enc_AuthorityMethod/2,
enc_Authority/2,
enc_File/2,
enc_Channel/2,
enc_MessageType/2,
enc_MessageStatus/2,
enc_MessageFeed/2,
enc_Message/2,
enc_Ack/2
]).

-export([
dec_OS/2,
dec_P2P/2,
dec_MUC/2,
dec_CHATString/2,
dec_Feature/2,
dec_AuthorityMethod/2,
dec_Authority/2,
dec_File/2,
dec_Channel/2,
dec_MessageType/2,
dec_MessageStatus/2,
dec_MessageFeed/2,
dec_Message/2,
dec_Ack/2
]).

-export([info/0]).

-export([encode/2,decode/2]).

encoding_rule() -> ber.

maps() -> false.

bit_string_format() -> bitstring.

legacy_erlang_types() -> false.

encode(Type, Data) ->
try iolist_to_binary(element(1, encode_disp(Type, Data))) of
  Bytes ->
    {ok,Bytes}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.


decode(Type, Data) ->
try
   Result = decode_disp(Type, element(1, ber_decode_nif(Data))),
   {ok,Result}
  catch
    Class:Exception:Stk when Class =:= error; Class =:= exit ->
      case Exception of
        {error,{asn1,Reason}} ->
          {error,{asn1,{Reason,Stk}}};
        Reason ->
         {error,{asn1,{Reason,Stk}}}
      end
end.

encode_disp('OS', Data) -> enc_OS(Data);
encode_disp('P2P', Data) -> enc_P2P(Data);
encode_disp('MUC', Data) -> enc_MUC(Data);
encode_disp('CHATString', Data) -> enc_CHATString(Data);
encode_disp('Feature', Data) -> enc_Feature(Data);
encode_disp('AuthorityMethod', Data) -> enc_AuthorityMethod(Data);
encode_disp('Authority', Data) -> enc_Authority(Data);
encode_disp('File', Data) -> enc_File(Data);
encode_disp('Channel', Data) -> enc_Channel(Data);
encode_disp('MessageType', Data) -> enc_MessageType(Data);
encode_disp('MessageStatus', Data) -> enc_MessageStatus(Data);
encode_disp('MessageFeed', Data) -> enc_MessageFeed(Data);
encode_disp('Message', Data) -> enc_Message(Data);
encode_disp('Ack', Data) -> enc_Ack(Data);
encode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

decode_disp('OS', Data) -> dec_OS(Data);
decode_disp('P2P', Data) -> dec_P2P(Data);
decode_disp('MUC', Data) -> dec_MUC(Data);
decode_disp('CHATString', Data) -> dec_CHATString(Data);
decode_disp('Feature', Data) -> dec_Feature(Data);
decode_disp('AuthorityMethod', Data) -> dec_AuthorityMethod(Data);
decode_disp('Authority', Data) -> dec_Authority(Data);
decode_disp('File', Data) -> dec_File(Data);
decode_disp('Channel', Data) -> dec_Channel(Data);
decode_disp('MessageType', Data) -> dec_MessageType(Data);
decode_disp('MessageStatus', Data) -> dec_MessageStatus(Data);
decode_disp('MessageFeed', Data) -> dec_MessageFeed(Data);
decode_disp('Message', Data) -> dec_Message(Data);
decode_disp('Ack', Data) -> dec_Ack(Data);
decode_disp(Type, _Data) -> exit({error,{asn1,{undefined_type,Type}}}).

info() ->
   case ?MODULE:module_info(attributes) of
     Attributes when is_list(Attributes) ->
       case lists:keyfind(asn1_info, 1, Attributes) of
         {_,Info} when is_list(Info) ->
           Info;
         _ ->
           []
       end;
     _ ->
       []
   end.


%%================================
%%  OS
%%================================
enc_OS(Val) ->
    enc_OS(Val, [<<10>>]).

enc_OS(Val, TagIn) ->
case Val of
apple -> encode_tags(TagIn, [1], 1);
microsoft -> encode_tags(TagIn, [2], 1);
google -> encode_tags(TagIn, [3], 1);
ericsson -> encode_tags(TagIn, [4], 1);
nokia -> encode_tags(TagIn, [5], 1);
cisco -> encode_tags(TagIn, [6], 1);
Enumval1 -> exit({error,{asn1, {enumerated_not_in_range,Enumval1}}})
end.


dec_OS(Tlv) ->
   dec_OS(Tlv, [10]).

dec_OS(Tlv, TagIn) ->
case decode_integer(Tlv, TagIn) of
1 -> apple;
2 -> microsoft;
3 -> google;
4 -> ericsson;
5 -> nokia;
6 -> cisco;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end.



%%================================
%%  P2P
%%================================
enc_P2P(Val) ->
    enc_P2P(Val, [<<48>>]).

enc_P2P(Val, TagIn) ->
{_,Cindex1,Cindex2} = Val,

%%-------------------------------------------------
%% attribute from(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute to(2) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes2,EncLen2} = encode_restricted_string(Cindex2, [<<4>>]),

   BytesSoFar = [EncBytes1, EncBytes2],
LenSoFar = EncLen1 + EncLen2,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_P2P(Tlv) ->
   dec_P2P(Tlv, [16]).

dec_P2P(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute from(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute to(2) with type OCTET STRING
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = decode_octet_string(V2, [4]),

case Tlv3 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv3}}}) % extra fields not allowed
end,
Res1 = {'P2P',Term1,Term2},
Res1.


%%================================
%%  MUC
%%================================
enc_MUC(Val) ->
    enc_MUC(Val, [<<48>>]).

enc_MUC(Val, TagIn) ->
{_,Cindex1} = Val,

%%-------------------------------------------------
%% attribute room(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

   BytesSoFar = [EncBytes1],
LenSoFar = EncLen1,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_MUC(Tlv) ->
   dec_MUC(Tlv, [16]).

dec_MUC(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute room(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

case Tlv2 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv2}}}) % extra fields not allowed
end,
Res1 = {'MUC',Term1},
Res1.


%%================================
%%  CHATString
%%================================
enc_CHATString(Val) ->
    enc_CHATString(Val, [<<4>>]).

enc_CHATString(Val, TagIn) ->
encode_restricted_string(Val, TagIn).


dec_CHATString(Tlv) ->
   dec_CHATString(Tlv, [4]).

dec_CHATString(Tlv, TagIn) ->
decode_octet_string(Tlv, TagIn).



%%================================
%%  Feature
%%================================
enc_Feature(Val) ->
    enc_Feature(Val, [<<48>>]).

enc_Feature(Val, TagIn) ->
{_,Cindex1,Cindex2,Cindex3,Cindex4} = Val,

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute key(2) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes2,EncLen2} = encode_restricted_string(Cindex2, [<<4>>]),

%%-------------------------------------------------
%% attribute value(3) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes3,EncLen3} = encode_restricted_string(Cindex3, [<<4>>]),

%%-------------------------------------------------
%% attribute group(4) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes4,EncLen4} = encode_restricted_string(Cindex4, [<<4>>]),

   BytesSoFar = [EncBytes1, EncBytes2, EncBytes3, EncBytes4],
LenSoFar = EncLen1 + EncLen2 + EncLen3 + EncLen4,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_Feature(Tlv) ->
   dec_Feature(Tlv, [16]).

dec_Feature(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute key(2) with type OCTET STRING
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = decode_octet_string(V2, [4]),

%%-------------------------------------------------
%% attribute value(3) with type OCTET STRING
%%-------------------------------------------------
[V3|Tlv4] = Tlv3, 
Term3 = decode_octet_string(V3, [4]),

%%-------------------------------------------------
%% attribute group(4) with type OCTET STRING
%%-------------------------------------------------
[V4|Tlv5] = Tlv4, 
Term4 = decode_octet_string(V4, [4]),

case Tlv5 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv5}}}) % extra fields not allowed
end,
Res1 = {'Feature',Term1,Term2,Term3,Term4},
Res1.


%%================================
%%  AuthorityMethod
%%================================
enc_AuthorityMethod(Val) ->
    enc_AuthorityMethod(Val, [<<10>>]).

enc_AuthorityMethod(Val, TagIn) ->
case Val of
announce -> encode_tags(TagIn, [0], 1);
register -> encode_tags(TagIn, [1], 1);
authenticate -> encode_tags(TagIn, [2], 1);
dismiss -> encode_tags(TagIn, [3], 1);
renew -> encode_tags(TagIn, [4], 1);
Enumval1 -> exit({error,{asn1, {enumerated_not_in_range,Enumval1}}})
end.


dec_AuthorityMethod(Tlv) ->
   dec_AuthorityMethod(Tlv, [10]).

dec_AuthorityMethod(Tlv, TagIn) ->
case decode_integer(Tlv, TagIn) of
0 -> announce;
1 -> register;
2 -> authenticate;
3 -> dismiss;
4 -> renew;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end.



%%================================
%%  Authority
%%================================
enc_Authority(Val) ->
    enc_Authority(Val, [<<48>>]).

enc_Authority(Val, TagIn) ->
{_,Cindex1,Cindex2,Cindex3,Cindex4} = Val,

%%-------------------------------------------------
%% attribute session(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute type(2) with type ENUMERATED
%%-------------------------------------------------
   {EncBytes2,EncLen2} = case Cindex2 of
announce -> encode_tags([<<10>>], [0], 1);
register -> encode_tags([<<10>>], [1], 1);
authenticate -> encode_tags([<<10>>], [2], 1);
dismiss -> encode_tags([<<10>>], [3], 1);
renew -> encode_tags([<<10>>], [4], 1);
Enumval2 -> exit({error,{asn1, {enumerated_not_in_range,Enumval2}}})
end,

%%-------------------------------------------------
%% attribute cert(3) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes3,EncLen3} = encode_restricted_string(Cindex3, [<<4>>]),

%%-------------------------------------------------
%% attribute settings(4) with type SEQUENCE OF
%%-------------------------------------------------
   {EncBytes4,EncLen4} = 'enc_Authority_settings'(Cindex4, [<<48>>]),

   BytesSoFar = [EncBytes1, EncBytes2, EncBytes3, EncBytes4],
LenSoFar = EncLen1 + EncLen2 + EncLen3 + EncLen4,
encode_tags(TagIn, BytesSoFar, LenSoFar).



%%================================
%%  Authority_settings
%%================================
enc_Authority_settings(Val, TagIn) ->
      {EncBytes,EncLen} = 'enc_Authority_settings_components'(Val,[],0),
   encode_tags(TagIn, EncBytes, EncLen).

'enc_Authority_settings_components'([], AccBytes, AccLen) -> 
   {lists:reverse(AccBytes),AccLen};

'enc_Authority_settings_components'([H|T],AccBytes, AccLen) ->
   {EncBytes,EncLen} = 'enc_Feature'(H, [<<48>>]),
   'enc_Authority_settings_components'(T,[EncBytes|AccBytes], AccLen + EncLen).



dec_Authority(Tlv) ->
   dec_Authority(Tlv, [16]).

dec_Authority(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute session(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute type(2) with type ENUMERATED
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = case decode_integer(V2, [10]) of
0 -> announce;
1 -> register;
2 -> authenticate;
3 -> dismiss;
4 -> renew;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end,

%%-------------------------------------------------
%% attribute cert(3) with type OCTET STRING
%%-------------------------------------------------
[V3|Tlv4] = Tlv3, 
Term3 = decode_octet_string(V3, [4]),

%%-------------------------------------------------
%% attribute settings(4) with type SEQUENCE OF
%%-------------------------------------------------
[V4|Tlv5] = Tlv4, 
Term4 = 'dec_Authority_settings'(V4, [16]),

case Tlv5 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv5}}}) % extra fields not allowed
end,
Res1 = {'Authority',Term1,Term2,Term3,Term4},
Res1.
'dec_Authority_settings'(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),
['dec_Feature'(V1, [16]) || V1 <- Tlv1].




%%================================
%%  File
%%================================
enc_File(Val) ->
    enc_File(Val, [<<48>>]).

enc_File(Val, TagIn) ->
{_,Cindex1,Cindex2,Cindex3,Cindex4} = Val,

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute mime(2) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes2,EncLen2} = encode_restricted_string(Cindex2, [<<4>>]),

%%-------------------------------------------------
%% attribute payload(3) with type ASN1_OPEN_TYPE
%%-------------------------------------------------
   {EncBytes3,EncLen3} = encode_open_type(Cindex3, []),

%%-------------------------------------------------
%% attribute parentid(4) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes4,EncLen4} = encode_restricted_string(Cindex4, [<<4>>]),

   BytesSoFar = [EncBytes1, EncBytes2, EncBytes3, EncBytes4],
LenSoFar = EncLen1 + EncLen2 + EncLen3 + EncLen4,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_File(Tlv) ->
   dec_File(Tlv, [16]).

dec_File(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute mime(2) with type OCTET STRING
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = decode_octet_string(V2, [4]),

%%-------------------------------------------------
%% attribute payload(3) with type ASN1_OPEN_TYPE
%%-------------------------------------------------
[V3|Tlv4] = Tlv3, 
Term3 = decode_open_type_as_binary(V3, []),

%%-------------------------------------------------
%% attribute parentid(4) with type OCTET STRING
%%-------------------------------------------------
[V4|Tlv5] = Tlv4, 
Term4 = decode_octet_string(V4, [4]),

case Tlv5 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv5}}}) % extra fields not allowed
end,
Res1 = {'File',Term1,Term2,Term3,Term4},
Res1.


%%================================
%%  Channel
%%================================
enc_Channel(Val) ->
    enc_Channel(Val, [<<48>>]).

enc_Channel(Val, TagIn) ->
{_,Cindex1} = Val,

%%-------------------------------------------------
%% attribute channel(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

   BytesSoFar = [EncBytes1],
LenSoFar = EncLen1,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_Channel(Tlv) ->
   dec_Channel(Tlv, [16]).

dec_Channel(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute channel(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

case Tlv2 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv2}}}) % extra fields not allowed
end,
Res1 = {'Channel',Term1},
Res1.


%%================================
%%  MessageType
%%================================
enc_MessageType(Val) ->
    enc_MessageType(Val, [<<10>>]).

enc_MessageType(Val, TagIn) ->
case Val of
sys -> encode_tags(TagIn, [1], 1);
reply -> encode_tags(TagIn, [2], 1);
forward -> encode_tags(TagIn, [3], 1);
read -> encode_tags(TagIn, [4], 1);
edited -> encode_tags(TagIn, [5], 1);
Enumval1 -> exit({error,{asn1, {enumerated_not_in_range,Enumval1}}})
end.


dec_MessageType(Tlv) ->
   dec_MessageType(Tlv, [10]).

dec_MessageType(Tlv, TagIn) ->
case decode_integer(Tlv, TagIn) of
1 -> sys;
2 -> reply;
3 -> forward;
4 -> read;
5 -> edited;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end.



%%================================
%%  MessageStatus
%%================================
enc_MessageStatus(Val) ->
    enc_MessageStatus(Val, [<<10>>]).

enc_MessageStatus(Val, TagIn) ->
case Val of
async -> encode_tags(TagIn, [1], 1);
delete -> encode_tags(TagIn, [2], 1);
clear -> encode_tags(TagIn, [3], 1);
update -> encode_tags(TagIn, [4], 1);
edit -> encode_tags(TagIn, [5], 1);
Enumval1 -> exit({error,{asn1, {enumerated_not_in_range,Enumval1}}})
end.


dec_MessageStatus(Tlv) ->
   dec_MessageStatus(Tlv, [10]).

dec_MessageStatus(Tlv, TagIn) ->
case decode_integer(Tlv, TagIn) of
1 -> async;
2 -> delete;
3 -> clear;
4 -> update;
5 -> edit;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end.



%%================================
%%  MessageFeed
%%================================
enc_MessageFeed(Val) ->
    enc_MessageFeed(Val, []).

enc_MessageFeed(Val, TagIn) ->
   {EncBytes,EncLen} = case element(1,Val) of
      p2p ->
         'enc_P2P'(element(2,Val), [<<48>>,<<160>>]);
      muc ->
         'enc_MUC'(element(2,Val), [<<48>>,<<161>>]);
      chan ->
         'enc_Channel'(element(2,Val), [<<48>>,<<162>>]);
      Else -> 
         exit({error,{asn1,{invalid_choice_type,Else}}})
   end,

encode_tags(TagIn, EncBytes, EncLen).




dec_MessageFeed(Tlv) ->
   dec_MessageFeed(Tlv, []).

dec_MessageFeed(Tlv, TagIn) ->
Tlv1 = match_tags(Tlv, TagIn),
case (case Tlv1 of [CtempTlv1] -> CtempTlv1; _ -> Tlv1 end) of

%% 'p2p'
    {131072, V1} -> 
        {p2p, 'dec_P2P'(V1, [16])};


%% 'muc'
    {131073, V1} -> 
        {muc, 'dec_MUC'(V1, [16])};


%% 'chan'
    {131074, V1} -> 
        {chan, 'dec_Channel'(V1, [16])};

      Else -> 
         exit({error,{asn1,{invalid_choice_tag,Else}}})
   end
.


%%================================
%%  Message
%%================================
enc_Message(Val) ->
    enc_Message(Val, [<<48>>]).

enc_Message(Val, TagIn) ->
{_,Cindex1,Cindex2,Cindex3,Cindex4,Cindex5,Cindex6,Cindex7,Cindex8,Cindex9,Cindex10,Cindex11} = Val,

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute feed(2)   External MESSAGE-v1:MessageFeed
%%-------------------------------------------------
   {EncBytes2,EncLen2} = 'enc_MessageFeed'(Cindex2, []),

%%-------------------------------------------------
%% attribute from(3) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes3,EncLen3} = encode_restricted_string(Cindex3, [<<4>>]),

%%-------------------------------------------------
%% attribute to(4) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes4,EncLen4} = encode_restricted_string(Cindex4, [<<4>>]),

%%-------------------------------------------------
%% attribute files(5) with type SEQUENCE OF
%%-------------------------------------------------
   {EncBytes5,EncLen5} = 'enc_Message_files'(Cindex5, [<<48>>]),

%%-------------------------------------------------
%% attribute type(6) with type ENUMERATED
%%-------------------------------------------------
   {EncBytes6,EncLen6} = case Cindex6 of
sys -> encode_tags([<<10>>], [1], 1);
reply -> encode_tags([<<10>>], [2], 1);
forward -> encode_tags([<<10>>], [3], 1);
read -> encode_tags([<<10>>], [4], 1);
edited -> encode_tags([<<10>>], [5], 1);
Enumval4 -> exit({error,{asn1, {enumerated_not_in_range,Enumval4}}})
end,

%%-------------------------------------------------
%% attribute link(7) with type CHOICE
%%-------------------------------------------------
   {EncBytes7,EncLen7} = 'enc_Message_link'(Cindex7, []),

%%-------------------------------------------------
%% attribute seenby(8) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes8,EncLen8} = encode_restricted_string(Cindex8, [<<4>>]),

%%-------------------------------------------------
%% attribute repliedby(9) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes9,EncLen9} = encode_restricted_string(Cindex9, [<<4>>]),

%%-------------------------------------------------
%% attribute mentioned(10) with type SEQUENCE OF
%%-------------------------------------------------
   {EncBytes10,EncLen10} = 'enc_Message_mentioned'(Cindex10, [<<48>>]),

%%-------------------------------------------------
%% attribute status(11) with type ENUMERATED DEFAULT = clear
%%-------------------------------------------------
   {EncBytes11,EncLen11} =  case Cindex11 of
         asn1_DEFAULT ->
            {<<>>,0};
         _ when Cindex11 =:= clear ->
            {<<>>,0};
         _ ->
            case Cindex11 of
async -> encode_tags([<<10>>], [1], 1);
delete -> encode_tags([<<10>>], [2], 1);
clear -> encode_tags([<<10>>], [3], 1);
update -> encode_tags([<<10>>], [4], 1);
edit -> encode_tags([<<10>>], [5], 1);
Enumval7 -> exit({error,{asn1, {enumerated_not_in_range,Enumval7}}})
end
       end,

   BytesSoFar = [EncBytes1, EncBytes2, EncBytes3, EncBytes4, EncBytes5, EncBytes6, EncBytes7, EncBytes8, EncBytes9, EncBytes10, EncBytes11],
LenSoFar = EncLen1 + EncLen2 + EncLen3 + EncLen4 + EncLen5 + EncLen6 + EncLen7 + EncLen8 + EncLen9 + EncLen10 + EncLen11,
encode_tags(TagIn, BytesSoFar, LenSoFar).



%%================================
%%  Message_files
%%================================
enc_Message_files(Val, TagIn) ->
      {EncBytes,EncLen} = 'enc_Message_files_components'(Val,[],0),
   encode_tags(TagIn, EncBytes, EncLen).

'enc_Message_files_components'([], AccBytes, AccLen) -> 
   {lists:reverse(AccBytes),AccLen};

'enc_Message_files_components'([H|T],AccBytes, AccLen) ->
   {EncBytes,EncLen} = 'enc_File'(H, [<<48>>]),
   'enc_Message_files_components'(T,[EncBytes|AccBytes], AccLen + EncLen).




%%================================
%%  Message_link
%%================================
enc_Message_link(Val, TagIn) ->
      {EncBytes,EncLen} = case element(1,Val) of
      empty ->
         encode_null(element(2,Val), [<<5>>,<<161>>]);
      message ->
         'enc_Message'(element(2,Val), [<<48>>,<<162>>]);
      Else -> 
         exit({error,{asn1,{invalid_choice_type,Else}}})
   end,

encode_tags(TagIn, EncBytes, EncLen).





%%================================
%%  Message_mentioned
%%================================
enc_Message_mentioned(Val, TagIn) ->
      {EncBytes,EncLen} = 'enc_Message_mentioned_components'(Val,[],0),
   encode_tags(TagIn, EncBytes, EncLen).

'enc_Message_mentioned_components'([], AccBytes, AccLen) -> 
   {lists:reverse(AccBytes),AccLen};

'enc_Message_mentioned_components'([H|T],AccBytes, AccLen) ->
   {EncBytes,EncLen} = encode_restricted_string(H, [<<4>>]),
   'enc_Message_mentioned_components'(T,[EncBytes|AccBytes], AccLen + EncLen).



dec_Message(Tlv) ->
   dec_Message(Tlv, [16]).

dec_Message(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute id(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute feed(2)   External MESSAGE-v1:MessageFeed
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = 'dec_MessageFeed'(V2, []),

%%-------------------------------------------------
%% attribute from(3) with type OCTET STRING
%%-------------------------------------------------
[V3|Tlv4] = Tlv3, 
Term3 = decode_octet_string(V3, [4]),

%%-------------------------------------------------
%% attribute to(4) with type OCTET STRING
%%-------------------------------------------------
[V4|Tlv5] = Tlv4, 
Term4 = decode_octet_string(V4, [4]),

%%-------------------------------------------------
%% attribute files(5) with type SEQUENCE OF
%%-------------------------------------------------
[V5|Tlv6] = Tlv5, 
Term5 = 'dec_Message_files'(V5, [16]),

%%-------------------------------------------------
%% attribute type(6) with type ENUMERATED
%%-------------------------------------------------
[V6|Tlv7] = Tlv6, 
Term6 = case decode_integer(V6, [10]) of
1 -> sys;
2 -> reply;
3 -> forward;
4 -> read;
5 -> edited;
Default1 -> exit({error,{asn1,{illegal_enumerated,Default1}}})
end,

%%-------------------------------------------------
%% attribute link(7) with type CHOICE
%%-------------------------------------------------
[V7|Tlv8] = Tlv7, 
Term7 = 'dec_Message_link'(V7, []),

%%-------------------------------------------------
%% attribute seenby(8) with type OCTET STRING
%%-------------------------------------------------
[V8|Tlv9] = Tlv8, 
Term8 = decode_octet_string(V8, [4]),

%%-------------------------------------------------
%% attribute repliedby(9) with type OCTET STRING
%%-------------------------------------------------
[V9|Tlv10] = Tlv9, 
Term9 = decode_octet_string(V9, [4]),

%%-------------------------------------------------
%% attribute mentioned(10) with type SEQUENCE OF
%%-------------------------------------------------
[V10|Tlv11] = Tlv10, 
Term10 = 'dec_Message_mentioned'(V10, [16]),

%%-------------------------------------------------
%% attribute status(11) with type ENUMERATED DEFAULT = clear
%%-------------------------------------------------
{Term11,Tlv12} = case Tlv11 of
[{10,V11}|TempTlv12] ->
    {case decode_integer(V11, []) of
1 -> async;
2 -> delete;
3 -> clear;
4 -> update;
5 -> edit;
Default2 -> exit({error,{asn1,{illegal_enumerated,Default2}}})
end, TempTlv12};
    _ ->
        {clear,Tlv11}
end,

case Tlv12 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv12}}}) % extra fields not allowed
end,
Res1 = {'Message',Term1,Term2,Term3,Term4,Term5,Term6,Term7,Term8,Term9,Term10,Term11},
Res1.
'dec_Message_files'(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),
['dec_File'(V1, [16]) || V1 <- Tlv1].


'dec_Message_link'(Tlv, TagIn) ->
Tlv1 = match_tags(Tlv, TagIn),
case (case Tlv1 of [CtempTlv1] -> CtempTlv1; _ -> Tlv1 end) of

%% 'empty'
    {131073, V1} -> 
        {empty, decode_null(V1, [5])};


%% 'message'
    {131074, V1} -> 
        {message, 'dec_Message'(V1, [16])};

      Else -> 
         exit({error,{asn1,{invalid_choice_tag,Else}}})
   end
.
'dec_Message_mentioned'(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),
[decode_octet_string(V1, [4]) || V1 <- Tlv1].




%%================================
%%  Ack
%%================================
enc_Ack(Val) ->
    enc_Ack(Val, [<<48>>]).

enc_Ack(Val, TagIn) ->
{_,Cindex1,Cindex2} = Val,

%%-------------------------------------------------
%% attribute table(1) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes1,EncLen1} = encode_restricted_string(Cindex1, [<<4>>]),

%%-------------------------------------------------
%% attribute id(2) with type OCTET STRING
%%-------------------------------------------------
   {EncBytes2,EncLen2} = encode_restricted_string(Cindex2, [<<4>>]),

   BytesSoFar = [EncBytes1, EncBytes2],
LenSoFar = EncLen1 + EncLen2,
encode_tags(TagIn, BytesSoFar, LenSoFar).


dec_Ack(Tlv) ->
   dec_Ack(Tlv, [16]).

dec_Ack(Tlv, TagIn) ->
   %%-------------------------------------------------
   %% decode tag and length 
   %%-------------------------------------------------
Tlv1 = match_tags(Tlv, TagIn),

%%-------------------------------------------------
%% attribute table(1) with type OCTET STRING
%%-------------------------------------------------
[V1|Tlv2] = Tlv1, 
Term1 = decode_octet_string(V1, [4]),

%%-------------------------------------------------
%% attribute id(2) with type OCTET STRING
%%-------------------------------------------------
[V2|Tlv3] = Tlv2, 
Term2 = decode_octet_string(V2, [4]),

case Tlv3 of
[] -> true;_ -> exit({error,{asn1, {unexpected,Tlv3}}}) % extra fields not allowed
end,
Res1 = {'Ack',Term1,Term2},
Res1.

%%%
%%% Run-time functions.
%%%

'dialyzer-suppressions'(Arg) ->
    ok.

ber_decode_nif(B) ->
    asn1rt_nif:decode_ber_tlv(B).

ber_encode([Tlv]) ->
    ber_encode(Tlv);
ber_encode(Tlv) when is_binary(Tlv) ->
    Tlv;
ber_encode(Tlv) ->
    asn1rt_nif:encode_ber_tlv(Tlv).

collect_parts(TlvList) ->
    collect_parts(TlvList, []).

collect_parts([{_, L} | Rest], Acc) when is_list(L) ->
    collect_parts(Rest, [collect_parts(L) | Acc]);
collect_parts([{3, <<Unused,Bits/binary>>} | Rest], _Acc) ->
    collect_parts_bit(Rest, [Bits], Unused);
collect_parts([{_T, V} | Rest], Acc) ->
    collect_parts(Rest, [V | Acc]);
collect_parts([], Acc) ->
    list_to_binary(lists:reverse(Acc)).

collect_parts_bit([{3, <<Unused,Bits/binary>>} | Rest], Acc, Uacc) ->
    collect_parts_bit(Rest, [Bits | Acc], Unused + Uacc);
collect_parts_bit([], Acc, Uacc) ->
    list_to_binary([Uacc | lists:reverse(Acc)]).

decode_integer(Tlv, TagIn) ->
    Bin = match_tags(Tlv, TagIn),
    Len = byte_size(Bin),
    <<Int:Len/signed-unit:8>> = Bin,
    Int.

decode_null(Tlv, Tags) ->
    Val = match_tags(Tlv, Tags),
    case Val of
        <<>> ->
            'NULL';
        _ ->
            exit({error, {asn1, {decode_null, Val}}})
    end.

decode_octet_string(Tlv, TagsIn) ->
    Bin = match_and_collect(Tlv, TagsIn),
    binary:copy(Bin).

decode_open_type_as_binary(Tlv, TagIn) ->
    ber_encode(match_tags(Tlv, TagIn)).

encode_length(L) when L =< 127 ->
    {[L], 1};
encode_length(L) ->
    Oct = minimum_octets(L),
    Len = length(Oct),
    if
        Len =< 126 ->
            {[128 bor Len | Oct], Len + 1};
        true ->
            exit({error, {asn1, too_long_length_oct, Len}})
    end.

encode_null(_Val, TagIn) ->
    encode_tags(TagIn, [], 0).

encode_open_type(Val, T) when is_list(Val) ->
    encode_open_type(list_to_binary(Val), T);
encode_open_type(Val, Tag) ->
    encode_tags(Tag, Val, byte_size(Val)).

encode_restricted_string(OctetList, TagIn) when is_binary(OctetList) ->
    encode_tags(TagIn, OctetList, byte_size(OctetList));
encode_restricted_string(OctetList, TagIn) when is_list(OctetList) ->
    encode_tags(TagIn, OctetList, length(OctetList)).

encode_tags([Tag | Trest], BytesSoFar, LenSoFar) ->
    {Bytes2, L2} = encode_length(LenSoFar),
    encode_tags(Trest,
                [Tag, Bytes2 | BytesSoFar],
                LenSoFar + byte_size(Tag) + L2);
encode_tags([], BytesSoFar, LenSoFar) ->
    {BytesSoFar, LenSoFar}.

match_and_collect(Tlv, TagsIn) ->
    Val = match_tags(Tlv, TagsIn),
    case Val of
        [_ | _] = PartList ->
            collect_parts(PartList);
        Bin when is_binary(Bin) ->
            Bin
    end.

match_tags({T, V}, [T]) ->
    V;
match_tags({T, V}, [T | Tt]) ->
    match_tags(V, Tt);
match_tags([{T, V}], [T | Tt]) ->
    match_tags(V, Tt);
match_tags([{T, _V} | _] = Vlist, [T]) ->
    Vlist;
match_tags(Tlv, []) ->
    Tlv;
match_tags({Tag, _V} = Tlv, [T | _Tt]) ->
    exit({error, {asn1, {wrong_tag, {{expected, T}, {got, Tag, Tlv}}}}}).

minimum_octets(0, Acc) ->
    Acc;
minimum_octets(Val, Acc) ->
    minimum_octets(Val bsr 8, [Val band 255 | Acc]).

minimum_octets(Val) ->
    minimum_octets(Val, []).
