-module(service_friend).
-include_lib("service/include/feature.hrl").
-include_lib("service/include/friend.hrl").
-include_lib("service/include/roster.hrl").
-compile({parse_transform, bert_google}).
